//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSieuThi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GianHangChung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GianHangChung()
        {
            this.MatHangChungs = new HashSet<MatHangChung>();
        }
    
        public int GianHangChungId { get; set; }
        public string MaGianHangChung { get; set; }
        public string TenGianHangChung { get; set; }
        public Nullable<int> HeThongId { get; set; }
        public string AnhGianHang { get; set; }
    
        public virtual HeThong HeThong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatHangChung> MatHangChungs { get; set; }
    }
}
