//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSieuThi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeThong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeThong()
        {
            this.GianHangChungs = new HashSet<GianHangChung>();
            this.SieuThis = new HashSet<SieuThi>();
            this.SuKienChungs = new HashSet<SuKienChung>();
        }
    
        public int HeThongId { get; set; }
        public string TenHeThong { get; set; }
        public string LoaiHinhKD { get; set; }
        public string Country { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Picture_GP_KD { get; set; }
        public string AnhIcon { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SoLuotSukien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GianHangChung> GianHangChungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SieuThi> SieuThis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKienChung> SuKienChungs { get; set; }
    }
}
