//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSieuThi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sieuthiapiEntities : DbContext
    {
        public sieuthiapiEntities()
            : base("name=sieuthiapiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DonDatHang> DonDatHangs { get; set; }
        public virtual DbSet<GianHang> GianHangs { get; set; }
        public virtual DbSet<GianHangChung> GianHangChungs { get; set; }
        public virtual DbSet<HeThong> HeThongs { get; set; }
        public virtual DbSet<MatHang> MatHangs { get; set; }
        public virtual DbSet<MatHangChung> MatHangChungs { get; set; }
        public virtual DbSet<SieuThi> SieuThis { get; set; }
        public virtual DbSet<SuKien> SuKiens { get; set; }
        public virtual DbSet<SuKienChung> SuKienChungs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
