//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSieuThi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SieuThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SieuThi()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
            this.GianHangs = new HashSet<GianHang>();
            this.SuKiens = new HashSet<SuKien>();
        }
    
        public int SieuThiId { get; set; }
        public string TenSieuThi { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string CuocPhiVC { get; set; }
        public Nullable<int> HeThongId { get; set; }
        public string longlat { get; set; }
        public string Email { get; set; }
        public string pass { get; set; }
        public string GioMoCua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GianHang> GianHangs { get; set; }
        public virtual HeThong HeThong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKien> SuKiens { get; set; }
    }
}
