//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSieuThi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public int SuKienId { get; set; }
        public string DsAnh { get; set; }
        public string NDSuKien { get; set; }
        public Nullable<int> SieuThiId { get; set; }
        public string TDSuKien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> DaThongBao { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        public virtual SieuThi SieuThi { get; set; }
    }
}
